export enum AdminActionTypes {
  SET_USERS_DATA = "ADMIN/SET_USERS_DATA",
  SET_IS_LOGGED = "ADMIN/SET_IS_LOGGED",
  SET_IS_LOADING = "ADMIN/SET_IS_LOADING",
  SET_ERROR = "ADMIN/SET_ERROR",
  SET_IS_ERROR = "ADMIN/SET_IS_ERROR",
}
